layout_spectrum: 0.8305005
typography_spectrum: 0.4285835
color:
  saturation: 0.830827
  lightness: 0.5139635
  brandStrength: 0.9723657
  brandColors:
    - '#04919A'
    - '#FCFCFD'
    - '#C5DAE7'
    - '#88C7C6'
    - '#4A8AAA'
  rhythmicContrast: 0.2207304
name: HV Fotografía
